@API_HostAddress = https://localhost:7039/api

### Get All Categories
GET {{API_HostAddress}}/categories/all
Accept: application/json

### Get Category By Id
@categoryId = f7e0511b-6692-4af1-98cd-105caadd16be
GET {{API_HostAddress}}/categories/{{categoryId}}
Accept: application/json

### Post Category
POST {{API_HostAddress}}/categories
Accept: application/json
Content-type: application/json
{
  "name": "Gasto com internet",
  "description": "Gasto com internet"
}

### Get All Transactions
GET {{API_HostAddress}}/transactions/all
Accept: application/json

### Get Transaction By Id
@transactionId = bc63de15-3254-4d26-b918-5b30e7fbfaef
GET {{API_HostAddress}}/transactions/{{transactionId}}
Accept: application/json

### Get Transaction By Status pending
GET {{API_HostAddress}}/transactions/status/Pending
Accept: application/json

### Get Transaction By Status paid
GET {{API_HostAddress}}/transactions/status/Paid
Accept: application/json

### Get Transaction By Status cancelled
GET {{API_HostAddress}}/transactions/status/Cancelled
Accept: application/json

### Get Transaction By Type expense
GET {{API_HostAddress}}/transactions/type/Expense
Accept: application/json

### Get Transaction By Type revenue
GET {{API_HostAddress}}/transactions/type/Revenue
Accept: application/json

### PUT Pay Transaction
PUT {{API_HostAddress}}/transactions/pay/bc63de15-3254-4d26-b918-5b30e7fbfaef
Accept: application/json
Content-type: application/json
{
  "paymentDate": "2026-02-03T03:08:19.339"
}

### PUT Reopen Transaction
PUT {{API_HostAddress}}/transactions/reopen/bc63de15-3254-4d26-b918-5b30e7fbfaef
Accept: application/json
Content-type: application/json

### PUT Cancel Transaction
PUT {{API_HostAddress}}/transactions/cancel/f76a0610-2d57-4be5-b46c-85c5b3fa8545
Accept: application/json
Content-type: application/json

### POST Create Transaction
POST {{API_HostAddress}}/transactions
Accept: application/json
Content-type: application/json
{
  "description": "Transaction Test",
  "amount": 3125,
  "dueDate": "2026-02-03T03:08:19.338Z",
  "transactionType": "revenue",
  "categoryId": "f7e0511b-6692-4af1-98cd-105caadd16be",
  "createdAt": "2026-02-03T03:08:19.338Z"
}